import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Box} from '@chakra-ui/react'

export default function Home() {



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<div>

 
  


 <h1 className='lg:bg-green-300'>maher</h1>
 

 



</div>


    </div>
  )
}
