import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<div>

  nxt app
 

  <video id='video' controls="controls" preload='none' width="600" poster="https://assets.codepen.io/32795/poster.png">
    <source id='mp4' src="http://media.w3.org/2010/05/sintel/trailer.mp4" type='video/mp4' />
  
    </video>

 


{/* 
<video id='video' controls="controls" preload='none' width="600" poster="https://assets.codepen.io/32795/poster.png">

<source id='mp4' src="blob:https://player.vimeo.com/deb7190b-1e03-4f14-aa9f-04ccd63a1c60" type='video/mp4' />
  

  </video> */}
</div>


    </div>
  )
}
